### ISSUE TITLE
Escaping html entities

### ISSUE THREAD

**Issue by matthewdking** [Karyum/Create-Karyum-App#10]
[This](https://github.com/Karyum/React-Simple-Setup/blob/master/src/app.jsx#L3) can be rewritten with `;`

```
const App = () => <h1 className="app"> Hey I&lsquo;m React&lsquo;s setup </h1>;
```

**Comment by Karyum** [comment]
That's ridiculous but i'll make a PR

**Comment by Karyum** [comment]
@matthewdking would you fix it by disabling this rule in eslint or change it the way you did ?
can it even be disabled with eslint

**Comment by matthewdking** [comment]
@Karyum This can't be disabled with eslint. It's not a linter error its to do with the way react/jsx renders specific characters. So characters such as `'` need to be written like this `&lsquo;`.
