### ISSUE TITLE
devdep and dep in package.json

### ISSUE THREAD

**Issue by jbesraa** [Karyum/Create-Karyum-App#3]
things you are gonna need in production should be in dep, otherwise in devdep.

**Comment by Karyum** [comment]
@esraajb So do i currently have a package which should be somewhere else ? and what is it ?

**Comment by jbesraa** [comment]
webpack and everything else that you are using from babel which is not for testing.

**Comment by Karyum** [comment]
https://stackoverflow.com/questions/40143357/do-you-put-babel-and-webpack-in-devdependencies-or-dependencies
If i have the bundle then i won't need webpack anymore in production nor babel, in case i need babel i would have the .babelrc file
